travis:
  secure:
    BINSTAR_TOKEN: ff2NxtVCul4d65R2QamhiN1uDl18swfGP4rypJiiwgqCoH2OzlznC8BrQG/2wDl7m3CRgbhJnGrBOgP8tZB5zYBokPFmAuk5y+UZLgAQAMP4WBq1HB7hCXDJUSEOOFsKnfYVMMFEthVfPBm6ZEmHJpFtwSylOIlZjGRvmxzrtNBW6Iy5fbAmf+5rZ1zoIBSrUsnsF4Ml/mKr4SmxAMrgrPPufBHVsRK3xesUcx1I1E3VJ1P1dyLxUodyO+MNgxZ/uYqY2AebUk5sEeroJ4rLacXzupV0LJXa11gYslYVnnyqthaHW9uVSFAspCo6k3iRrjFusGXYsA1eJTmY6zg5PO++wLbmBVZlZmV+FCdJ/VasfnWkvbtzN9s9W/pO680U7v/8GIDvsqEpdL2JV+iAAXAbHjeXG3xEH8EKCegl1ssIP6jmdypD4PjPien1hbv2FWMxKoD1SBI3w5n4gpsFHiXQOGG9kOS+WSSz63OF7yjfaVjy5SRjDHIgP1H9fuVEkFQTcs54ceDgOQcDeNvlgQ9ULznXLLZ7JTdc/Jll6djO8uNKFQ/KttxPIEUPg9kbUAdWtHX0UI8vM+jbhtuZ/wvSZnIh1ftnPry+i1QxrMYzvx0wxNPgjJCdWAjmf95xfpVJhsFiuCvVPeYc4LOUP43BMH2WO8A+clXwSendAV0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
